version: "3.5"

services:
    redis:
        image: redis
        ports:
            - 6379:6379
    mysql:
        image: mysql:5.7
        volumes:
            - ./data/db_data:/var/lib/mysql
        restart: always
        environment:
            - MYSQL_DATABASE=demo
            - MYSQL_USER=default_user
            - MYSQL_PASSWORD=FegKmfdaKMM8C27D
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - EXTERNAL_IP=0.0.0.0
        ports:
            - "8080:80"
        depends_on:
                - "mysql"
